import { defineConfig } from "vite";
import type { Plugin } from "vite";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import builtins from "builtin-modules";

const __dirname = dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/
`;

function prependMainJsBanner(text: string): Plugin {
	return {
		name: "prepend-main-js-banner",
		generateBundle(_opts, bundle) {
			for (const item of Object.values(bundle)) {
				if (item.type === "chunk" && item.fileName === "main.js") {
					item.code = text + item.code;
				}
			}
		},
	};
}

const external = [
	"obsidian",
	"electron",
	"@codemirror/autocomplete",
	"@codemirror/collab",
	"@codemirror/commands",
	"@codemirror/language",
	"@codemirror/lint",
	"@codemirror/search",
	"@codemirror/state",
	"@codemirror/view",
	"@lezer/common",
	"@lezer/highlight",
	"@lezer/lr",
	...builtins,
];

// Vite emits `styles.css` at repo root; Obsidian loads that file automatically from the plugin folder.
export default defineConfig(({ mode }) => ({
	plugins: [prependMainJsBanner(banner)],
	build: {
		target: "es2018",
		outDir: ".",
		emptyOutDir: false,
		copyPublicDir: false,
		sourcemap: mode === "development" ? "inline" : false,
		minify: mode === "production",
		lib: {
			entry: resolve(__dirname, "src/main.ts"),
			formats: ["cjs"],
			fileName: () => "main.js",
		},
		rollupOptions: {
			external,
			output: {
				exports: "default",
				assetFileNames: "styles.css",
			},
		},
	},
}));
